@startuml
participant Usuario
participant Cancion 
participant Plataforma
database BD

Usuario -> Cancion : Seleccion de cancion
Cancion -> Plataforma : Solicitud de borrado
Plataforma -> BD : Confirmacion borrado
alt caso de exito
BD --> Plataforma : Borrado confirmado
Plataforma --> Usuario : Confirmacion de borrado
else algun problema o fallo
BD --> Plataforma : Borrado no realizado
Plataforma --> Usuario : Borrado no completado
end
  
@enduml
