@startuml
participant Usuario u
participant Cancion c

database BD

Usuario u -> Cancion c : Seleccion de cancion
Cancion -> Plataforma : Solicitud de modificacion
Plataforma -> BD : Confirmacion modificado
alt caso de exito
BD --> Plataforma : Modificacion confirmada
Plataforma --> Usuario : Confirmacion de modificacion
else algun problema o fallo
BD --> Plataforma : Modificacion no realizada
Plataforma --> Usuario : Modificacion no completada
end
  
@enduml
