@startuml
participant Usuario
participant Cancion 
participant Plataforma
database BD

Usuario -> Cancion : Seleccion de cancion
Cancion -> Plataforma : Solicitud de modificacion
Plataforma -> BD : Confirmacion modificado
alt caso de exito
BD --> Plataforma : Modificacion confirmada
Plataforma --> Usuario : Confirmacion de modificacion
else algun problema o fallo
BD --> Plataforma : Modificacion no realizada
Plataforma --> Usuario : Modificacion no completada
end
  
@enduml
