@startuml
participant Usuario
participant Plataforma 
database BD

Usuario -> Plataforma : Solicitud Registro
Plataforma -> BD : Alta registro
alt caso de exito
BD --> Plataforma : Alta confirmada
Plataforma --> Usuario : Confirmacion de registro
else algun problema o fallo
BD --> Plataforma : Alta no realizada
Plataforma --> Usuario : Registro no completado
end


    
@enduml
